const imageBase=new URL(document.currentScript.src).pathname.replace(/script\.js$/, '');
window.servicePhotos={"cooling":{"title":"Air conditioners","description":"Comfort for your home and workspace.","images":[{"src":"BASE_REPLACE_photos/cooling.jpg","alt":"Demo photo for Air conditioners"},{"src":"BASE_REPLACE_photos/cooling-detail.jpg","alt":"Demo photo for Air conditioners"}]},"freezers":{"title":"Upright & chest freezers","description":"Explore storage and refrigeration solutions.","images":[{"src":"BASE_REPLACE_photos/freezers.jpg","alt":"Demo photo for Upright & chest freezers"},{"src":"BASE_REPLACE_photos/freezers-detail.jpg","alt":"Demo photo for Upright & chest freezers"}]},"laundry":{"title":"Washers & dryers","description":"Practical appliances for your laundry routine.","images":[{"src":"BASE_REPLACE_photos/laundry.jpg","alt":"Demo photo for Washers & dryers"},{"src":"BASE_REPLACE_photos/laundry-detail.jpg","alt":"Demo photo for Washers & dryers"}]},"stoves":{"title":"Gas & electrical stoves","description":"Cooking essentials for everyday meals.","images":[{"src":"BASE_REPLACE_photos/stoves.jpg","alt":"Demo photo for Gas & electrical stoves"},{"src":"BASE_REPLACE_photos/stoves-detail.jpg","alt":"Demo photo for Gas & electrical stoves"}]},"parts":{"title":"Spare parts","description":"Identify the right part for your appliance.","images":[{"src":"BASE_REPLACE_photos/parts.jpg","alt":"Demo photo for Spare parts"},{"src":"BASE_REPLACE_photos/parts-detail.jpg","alt":"Demo photo for Spare parts"}]},"repairs":{"title":"Repairs","description":"Support when your equipment needs attention.","images":[{"src":"BASE_REPLACE_photos/repairs.jpg","alt":"Demo photo for Repairs"},{"src":"BASE_REPLACE_photos/repairs-detail.jpg","alt":"Demo photo for Repairs"}]},"maintenance":{"title":"Maintenance","description":"Regular care for dependable performance.","images":[{"src":"BASE_REPLACE_photos/maintenance.jpg","alt":"Demo photo for Maintenance"},{"src":"BASE_REPLACE_photos/maintenance-detail.jpg","alt":"Demo photo for Maintenance"}]}};
for(const item of Object.values(window.servicePhotos))for(const image of item.images)image.src=image.src.replace('BASE_REPLACE_',imageBase);
function initializePage(){
const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('nav');toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open)});nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');nav.querySelectorAll('a').forEach(a=>a.classList.remove('active'));link.classList.add('active')}));document.querySelector('#year').textContent=new Date().getFullYear();document.querySelector('#copy-enquiry')?.addEventListener('click',async()=>{const text='Enquiry for Modern Refrigeration Corporation\nInterest: '+document.querySelector('#topic').value+'\n'+document.querySelector('#message').value;const status=document.querySelector('#copy-status');try{await navigator.clipboard.writeText(text);status.textContent='Enquiry copied. It’s ready to share when contact details are available.'}catch{status.textContent='Copy is unavailable in this browser. Please select and copy your message manually.'}});

const carousel=document.querySelector('.hero-slideshow');if(carousel){const slides=[...carousel.querySelectorAll('.hero-slide')],dots=[...carousel.querySelectorAll('[data-slide]')],pause=carousel.querySelector('.slide-pause');let current=0,timer,paused=window.matchMedia('(prefers-reduced-motion: reduce)').matches;function show(index){current=(index+slides.length)%slides.length;slides.forEach((s,i)=>{s.classList.toggle('is-current',i===current);s.setAttribute('aria-hidden',String(i!==current))});dots.forEach((d,i)=>d.setAttribute('aria-pressed',String(i===current)));document.querySelector('#slide-kicker').textContent=slides[current].dataset.kicker;document.querySelector('#slide-caption').textContent=slides[current].dataset.caption;document.querySelector('#slide-index').textContent=String(current+1).padStart(2,'0')+' / 03'}function start(){clearInterval(timer);if(!paused&&!document.hidden)timer=setInterval(()=>show(current+1),6000);pause.textContent=paused?'Play':'Pause';pause.setAttribute('aria-label',paused?'Play slideshow':'Pause slideshow')}dots.forEach((dot,i)=>dot.addEventListener('click',()=>{show(i);start()}));carousel.querySelectorAll('[data-step]').forEach(b=>b.addEventListener('click',()=>{show(current+Number(b.dataset.step));start()}));pause.addEventListener('click',()=>{paused=!paused;start()});carousel.addEventListener('mouseenter',()=>clearInterval(timer));carousel.addEventListener('mouseleave',start);carousel.addEventListener('focusin',()=>clearInterval(timer));carousel.addEventListener('focusout',()=>{if(!carousel.contains(document.activeElement))start()});document.addEventListener('visibilitychange',start,{signal:pageLife.signal});stopCarousel=()=>clearInterval(timer);start()}
const gallery=document.querySelector('#service-gallery');if(gallery){const close=()=>gallery.close();gallery.querySelector('.gallery-close').addEventListener('click',close);gallery.addEventListener('click',e=>{if(e.target===gallery){const rect=gallery.getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)close()}});document.querySelectorAll('[data-service]').forEach(button=>button.addEventListener('click',()=>{const item=window.servicePhotos[button.dataset.service];document.querySelector('#gallery-title').textContent=item.title;document.querySelector('#gallery-description').textContent=item.description;const container=gallery.querySelector('.gallery-images');container.replaceChildren(...item.images.map(photo=>{const figure=document.createElement('figure'),image=document.createElement('img');image.src=photo.src;image.alt=photo.alt;figure.append(image);return figure}));gallery.showModal()}));}

}

const siteBase=new URL(document.currentScript.src).pathname.replace(/script\.js$/, '');
const pages=new Set(['/','/services/','/about/','/contact/']);
let pageLife=new AbortController(),stopCarousel=()=>{},activePage=location.pathname.slice(siteBase.length-1),currentRequest=0;
const pageCache=new Map();
function savedPage(){try{return sessionStorage.getItem('mrc-current-page')}catch{return null}}
function remember(page){try{sessionStorage.setItem('mrc-current-page',page)}catch{}}
function normalize(value){let p=value.replace(/index\.html$/,'');if(!p.endsWith('/'))p+='/';return p}
function setState(page,anchor,push){const state={mrcPage:page,anchor};history[push?'pushState':'replaceState'](state,'',siteBase);remember(page)}
function scrollPage(anchor,focus){const target=anchor?document.getElementById(anchor):document.querySelector('main');if(anchor&&target)target.scrollIntoView({behavior:'auto'});else window.scrollTo(0,0);if(focus){const heading=target?.querySelector('h1,h2')||document.querySelector('main h1');if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true})}}}
async function navigate(page,{anchor='',push=true,focus=true}={}){
  page=normalize(page);if(!pages.has(page))return;const request=++currentRequest;
  if(page===activePage){setState(page,anchor,push);scrollPage(anchor,focus);return}
  document.body.setAttribute('aria-busy','true');document.documentElement.classList.add('page-loading');
  try{
    let text=pageCache.get(page);if(!text){const response=await fetch(siteBase+page.slice(1)+'index.html',{cache:'no-cache'});if(!response.ok)throw Error('Page unavailable');text=await response.text();pageCache.set(page,text)}
    if(request!==currentRequest)return;
    const parsed=new DOMParser().parseFromString(text,'text/html');if(!parsed.querySelector('main'))throw Error('Missing page');
    stopCarousel();pageLife.abort();pageLife=new AbortController();document.title=parsed.title;
    const description=document.querySelector('meta[name="description"]');if(description)description.content=parsed.querySelector('meta[name="description"]')?.content||'';
    document.body.replaceChildren(...[...parsed.body.children].filter(node=>node.tagName!=='SCRIPT'));
    activePage=page;initializePage();setState(page,anchor,push);scrollPage(anchor,focus);
  }catch(error){if(request!==currentRequest)return;let notice=document.querySelector('#navigation-error');if(!notice){notice=document.createElement('p');notice.id='navigation-error';notice.setAttribute('role','alert');document.querySelector('main').prepend(notice)}notice.textContent='This page could not load. Please check your connection and try the menu again.'}
  finally{if(request===currentRequest){document.body.removeAttribute('aria-busy');document.documentElement.classList.remove('page-loading')}}
}
document.addEventListener('click',event=>{
  if(event.defaultPrevented||event.button!==0||event.ctrlKey||event.metaKey||event.shiftKey||event.altKey)return;
  const link=event.target.closest('a[href]');if(!link||link.target||link.hasAttribute('download'))return;
  const url=new URL(link.href,location.href);if(url.origin!==location.origin||url.search)return;
  const page=normalize(url.pathname.startsWith(siteBase)?url.pathname.slice(siteBase.length-1):'/unhandled/');if(!pages.has(page))return;
  event.preventDefault();navigate(page,{anchor:decodeURIComponent(url.hash.slice(1))});
});
window.addEventListener('popstate',event=>{const state=event.state;if(state?.mrcPage)navigate(state.mrcPage,{anchor:state.anchor||'',push:false})});
initializePage();
activePage=normalize(activePage);const initial=pages.has(activePage)&&activePage!=='/'?activePage:(pages.has(history.state?.mrcPage)?history.state.mrcPage:(pages.has(savedPage())?savedPage():'/'));
const initialAnchor=decodeURIComponent(location.hash.slice(1));
if(initial!==activePage)navigate(initial,{anchor:initialAnchor,push:false,focus:false});else{setState(initial,initialAnchor,false);if(initialAnchor)scrollPage(initialAnchor,false)}
